########################### Ahmad'S ENVIRONMENT
# Here are my 5 Docker Hosts:
# - Home Server (hs) - Proxmox LXC with Ubuntu Server 22.04
# - Media / Database Server (mds) - Proxmox LXC with Ubuntu Server 22.04
# - Web Server (ws) - Digital Ocean VPS with Ubuntu Server 22.04
# - Synology (ds918) - Synology DS918+
# - DNS / AdBlock Server (dns) - Raspberry Pi 4B with Raspberry Pi OS

########################### THIS COMPOSE FILE
# - Home Server (hs) - Proxmox LXC with Ubuntu Server 22.04
# - Prefix/suffix "hs" refers to the above host
# - Docker version 24.0.7, build afdd53b
# - Docker Compose version v2.21.0

########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

include:
  ########################### SERVICES
  # PREFIX hs = home server
  # HOSTNAME=hs - defined in .env
  # CORE
  - compose/$HOSTNAME/socket-proxy.yml
